FROM nginx:stable-alpine

RUN apk add --no-cache openssl && \
  mkdir -p /etc/nginx/certs && \
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -subj "/CN=localhost" \
    -keyout /etc/nginx/certs/selfsigned.key \
    -out /etc/nginx/certs/selfsigned.crt

COPY nginx.conf /etc/nginx/conf.d/default.conf



